#include <stdio.h>

FILE *file;

int CUE_SEED;
int NUM_RESERVOIRS;
int NUM_SENSORS;
int NUM_MOTORS;
int MAX_AXON_LENGTH;
int MAX_SYNAPSES;
int MAX_WEIGHT;
int MAX_CUE;
int SEARCH_RADIUS;

int ACTION_POTENTIAL;
int THRESHOLD;
int RECOVERY_PERIOD;
int RECOVERY_THRESHOLD;
int INITIAL_SYNAPSE_WEIGHT;
float CUE_CHANGE;
float WEIGHT_CHANGE;
float LIFESPAN_INCREASE;
float LIFESPAN_DECREASE;

int numNeurons;
